# **My First R Program**

1. Print

In [ ]:
print ("Hello Universe World")

[1] "Hello Universe World"

2. Variables & Data Types

In [ ]:
myString <- ("Hello World")
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class (myString)
class (num)
class (floatingNum)
class (isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operators

In [ ]:
x <- 5
y <- 3

add <- x + y
sub <- x - y
div <- x / y
mul <- x * y

print (add, sub)
print (add)
print (sub)
print (div)
print (mul)

cat("\n +", add)
cat("\n-", sub)
cat("\n/", div)
cat("\n*", mul)

[1] 8
[1] 8
[1] 2
[1] 1.666667
[1] 15

 + 8
- 2
/ 1.666667
* 15

4. User Input

In [ ]:
name = readline("Enter Name: ")
favColor <- readline("Enter Color: ")

print(paste("Name:", name))
print(paste("FavColor:", favColor))

Enter Name: Jean
Enter Color: Red
[1] "Name: Jean"
[1] "FavColor: Red"

5. Decision making

In [ ]:
grade <- readline("Enter Grade: ")

if(grade <75){
  print("Failed")
}else{
  print("Passed")
}

Enter Grade: 89
[1] "Passed"

6. Loop

In [ ]:
for (i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Functions

In [ ]:
addNumber <- function(a,b){
  return(a+b)
}

addNumber(8,9)

[1] 17

8. Vectors

In [ ]:
grades <- c(98, 86, 96, 83, 91)

grades

cat("\nMean:", mean(grades))
cat("\nMax:", max(grades))
cat("\nMin:", min(grades))
cat("\nSum:", sum(grades))
cat("\nLength:", length(grades))

[1] 98 86 96 83 91

Mean: 90.8
Max: 98
Min: 83
Sum: 454
Length: 5

9. Matrices

In [ ]:
A <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow=3)
A

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

10. Lists

In [ ]:
student <- list(
  Name = "Jean",
  Age= 21,
  GPA= 1.5
)

student

$Name
[1] "Jean"

$Age
[1] 21

$GPA
[1] 1.5

11. Data Frames & CSV save

In [ ]:
students <- data.frame(
  Name= c("Jean", "Peter", "MJ"),
  Age= c(23, 25, 28),
  GPA= c(1.5, 1.8, 1.6)
)


students

write.csv(students, ("students.csv"))

  Name  Age GPA
1 Jean  23  1.5
2 Peter 25  1.8
3 MJ    28  1.6

12. Reading CSV Files

In [ ]:
data <- read.csv("students.csv")

head(data)

summary(data)

  X Name  Age GPA
1 1 Jean  23  1.5
2 2 Peter 25  1.8
3 3 MJ    28  1.6

       X              Name        Age             GPA
 Min.   :1.0   Length   :3   Min.   :23.00   Min.   :1.500
 1st Qu.:1.5   N.unique :3   1st Qu.:24.00   1st Qu.:1.550
 Median :2.0   N.blank  :0   Median :25.00   Median :1.600
 Mean   :2.0   Min.nchar:2   Mean   :25.33   Mean   :1.633
 3rd Qu.:2.5   Max.nchar:5   3rd Qu.:26.50   3rd Qu.:1.700
 Max.   :3.0                 Max.   :28.00   Max.   :1.800